# Uncomment the next line to define a global platform for your project
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

platform :ios, '9.0'
target 'GPUImageDemo' do

  pod 'GPUImage'

end
